# .github/workflows/test.yml
name: Run Tests

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
        
    - name: Run tests
      run: npm run test run
      # This will fail the workflow if tests fail

    # Optional: Add status check in a simpler way
    - name: Check Test Status
      if: ${{ failure() }}
      run: |
        echo "Tests failed - Please fix before merging"
        exit 1
