# .github/workflows/test.yml
name: Run Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm run test run

    # Optional: Add status check
    - name: Report Status
      if: always()
      uses: actions/github-script@v6
      with:
        script: |
          const { conclusion } = context.payload.check_run;
          if (conclusion === 'failure') {
            core.setFailed('Tests must pass before merging');
          }